### ISSUE TITLE
Where should we charge fees?

### ISSUE THREAD

**Issue by AdamBLevine** [tokenly/swapbot#10]
We should charge flat fee per instance if for no reason but spam control, but where the rest of the monetization for the platform comes from is up for debate.  I see two primary avenues we can take, and perhaps the answer is both for different people.

1 - Bitcoin Fee
Since we already have to have people load up their swapbot with bitcoin to make the transaction fees, and since our distribution system uses below-normal fees, the platform could collect the difference between our lower fees and the normal counterwallet fees.  This would not be notable or felt as a cost by the swapbot end user or its operator, the miners work with either amount just as well.

2 - Swap Fee
This is more like what ebay does, the seller pays a % to the platform that enables the trade.

a Swap fee would probably be more lucrative but it's also more complicated, perhaps its better to be invisible and stick to a bitcoin fee but that requires more up front capital and if you're not selling your token for bitcoin explicitly it means you might have to buy more bitcoin to restock the machine, which would be exacerbated by the higher-than-neccesary-because-its-where-our-share-lives transaction fees.

**Comment by AdamBLevine** [comment]
I think my favorite approach is a bitcoin fee with a token that can replace the part of the bitcoin fee that is our share, which we will sell for a variety of tokens.

**Comment by cryptonaut420** [comment]
What if we only take fees on a certain set of tokens? So for example if you want to accept any of the popular tokens (BTC, XCP, LTBCOIN, SWARM, SJCX, FLDC), then we will take a few % cut off of any incoming amounts for those

**Comment by AdamBLevine** [comment]
My desire here is to have options so that different types of users can find a method that suits their needs and resources.  Some people will really hate a % cut.  We sorta have to trust that if people are conducting commerce, i.e. a machine is getting use that then whatever its trading must have value.

This is really an argument in favor of piling our fee into the bitcoin mining fee portion because that is token agnostic and we can still accept BTC, XCP, LTBC, etc. by making the token that replaces the tokenly share of the fee when used as a supplement.

**Comment by deweller** [comment]
So say a high-profile fundraiser wants to use us for their next crowdfund sale.  And say we are looking at stocking $250,000 USD worth of tokens.

In reality, this demands more attention than selling a few EARLY tokens.  A customer using this type of swapbot is going to want to have access to support if there are any issues.

So, I think we need to have the ability to charge more for a swapbot doing a large amount of value.  That leans toward the percentage cut.

But... I also don't like the complication of sending 2 transactions for each swap.  That is just too much.

So I say we charge a flat-fee plus a percentage.  And we require the bot to be preloaded with BTC to cover the percentage.

The admin report will show how much BTC is pre-paid, how much is available and how much has been assessed as a fee.

The bot will then periodically bill the account (say once a week, or once every 0.1 BTC) and send that BTC to us.

**Comment by AdamBLevine** [comment]
So high profile fundraiser wants to preload for 500 users, how much up front is that?

**Comment by deweller** [comment]
Using these tiny fees (which can be changed):
BTC Dust: 0.0000543
Fee: 0.0001
Escrow Dust: 0.000025

That comes out to **0.08965** BTC for transactions for 500 users.

0.0125 BTC of that would be recoverable from the multisig escrows at a later date.

**Comment by AdamBLevine** [comment]
That fee comes to about 2 cents per user, and here we're back to the possibility of a variable fee based on how much you pay in terms of up front cost.  I could see having a fee as high as .001 BTC (22 cents per swap ) for a very cheap to set up bot

What do you think about this sort of variable schema?

1. $1 creation fee + .001BTC fee per TX (22 cents) ($110 for 500 swaps)
2. $10 creation fee + .0005BTC fee per TX (10 cents) ($50 for 500 swaps)
3. $100 creation fee + .0001BTC fee per TX (2 cents) ($10 for 500 swaps)

**Comment by cryptonaut420** [comment]
Option 2 seems like a reasonable compromise

**Comment by AdamBLevine** [comment]
Of what I said above?  My suggestion actually was to offer some variety of all three

**Comment by cryptonaut420** [comment]
ah yes. Yep lets have the multiple pricing options available

**Comment by deweller** [comment]
I'm thinking that the address you pay the fees to is a different address than the swapbot address.  That way we have a separate record on the blockchain for all fee-related transactions.

**Comment by AdamBLevine** [comment]
Would that automatically forward some of the fee to the swapbot for fuel, or would the fuel be a separate pool from the fee that would need to be funded seperately?

**Comment by deweller** [comment]
The fuel needs to go to a different address.

But it would be nice if the user had to just pay one BTC transaction to get started.  So, perhaps as part of this, we receive the first payment and starting fuel as one payment and then forward the fuel ourselves to the swapbot address.

**Comment by deweller** [comment]
I am going this direction right now.  The initial creation fee will include the fuel.

So, if we require a minimum fuel of 0.01 BTC, then the minimum displayed price for starting a swapbot will be $1 + 0.01 BTC.

The swapbot will take initial payment at the payment address and then forward the fuel to the public bot address.

Any remaining fuel is refundable at the end of the swapbot's life.

**Comment by AdamBLevine** [comment]
That makes sense to me.

**Comment by cryptonaut420** [comment]
"fuel" is being used to pay for any transaction fees etc. (as well as our fees) correct? Doesnt it have to be on the same address as the main swapbot address, or are we able to source fees from other wallet addresses now?

**Comment by deweller** [comment]
There are 2 separate addresses managed by each swapbot.  1 is the payment address.  The second is the public exchange address for the bot.

The owner of the bot sends the initial creation fee + starting fuel to the payment address.  The swapbot then sends the fuel from the payment address to the bot's exchange address.

**Comment by cryptonaut420** [comment]
Right. So the payment address which holds the main fuel supply just periodically tops up the public address? Seems like it would be much easier if we could source the fees from a different address, save a few transactions (I think I remember the XCP devs were working on something like that).. but then I guess there is the dust outputs as well

**Comment by deweller** [comment]
The payment address only provides the starting fuel for the exchange address once.

If needed, we can add the ability to automatically top-up the fuel address from the payment address.  But I don't expect this to be an issue in the short term.  

The fuel consumed per swap is very small and should go away when using OP_RETURN.

**Comment by cryptonaut420** [comment]
makes sense, sounds good!

**Comment by deweller** [comment]
Completed by b3804a785ea2606958ae4c38aae2470eeb55bd55
