### ISSUE TITLE
Email Swapbot Head not matching Store swapbot

### ISSUE THREAD

**Issue by AdamBLevine** [tokenly/swapbot#100]
These should match

![image](https://cloud.githubusercontent.com/assets/6858319/7996106/e2d2e894-0ad1-11e5-974a-c89d702d1108.png)

![image](https://cloud.githubusercontent.com/assets/6858319/7996368/73c12dc8-0ad4-11e5-82d2-32835389418f.png)

**Comment by AdamBLevine** [comment]
The next two emails hit almost immediately, must have been some quick blocks.  The head changed again - it was this one for both the 2nd and 3rd email

![image](https://cloud.githubusercontent.com/assets/6858319/7996137/26d48c1e-0ad2-11e5-9ded-4d8324569550.png)

**Comment by AdamBLevine** [comment]
Seems to have resolved itself, hasn't been an issue in quite a number of tests

**Comment by deweller** [comment]
We're relying on a 3rd party service (http://robohash.org/) for this right
now. Maybe the service is unreliable?  We might want to build our own at
some point.

**Comment by AdamBLevine** [comment]
the robohash project is open source, we could just run our own instance of
the service in the interim?

https://github.com/e1ven/Robohash

**Comment by deweller** [comment]
Yep - that's what I was attempting to communicate when I said "build our own".

I'd probably like to run this one:  
https://github.com/alternatex/robohash.js

It has had some more recent effort put into it and it runs on nodejs which is a little easier to maintain for me.
