### ISSUE TITLE
Make Recent Swaps display Swap Details rather than addresses

### ISSUE THREAD

**Issue by AdamBLevine** [tokenly/swapbot#101]
![image](https://cloud.githubusercontent.com/assets/6858319/8044537/3ff635ea-0de2-11e5-9a55-c6e22e54c99e.png)

This shows how much the swapbot sent to whom, when and with how many confirmations.   

It would be more interesting and useful if the list were made to show What was swapped for What, when without displaying which address did the swapping unless they visit the tx receipt page.

I'd say the new text should read 

"Delivered {Amount sent} {token sent}s in exchange for {Amount Recieved} {Token Type Recieved}s at {Time at which third email is dispatched}.  {Swap Details}

**Comment by deweller** [comment]
@AdamBLevine - Recent swaps now look like this:

![swapbot___the_official_tokenly__bot](https://cloud.githubusercontent.com/assets/51414/9777809/00530c34-572e-11e5-8b90-3993ce9e652c.png)

Do you still want to modify the recent swaps message?

**Comment by AdamBLevine** [comment]
No, the current messaging is fine
