### ISSUE TITLE
Add "Other Tokens Accepted" to Step 1 of Swap

### ISSUE THREAD

**Issue by AdamBLevine** [tokenly/swapbot#105]
To complete #104 we need to add a second line of informative text to the front page swaps.

It could logicly go under each swap
![image](https://cloud.githubusercontent.com/assets/6858319/8110633/25f9be3c-1012-11e5-883f-f250980e4efa.png)

 or it could be a machine-wide setting that displays more like badges, perhaps just above the white of the page along the lower boundary of the blue header image 
![image](https://cloud.githubusercontent.com/assets/6858319/8110652/53f2975a-1012-11e5-9f15-e9889bb60a0b.png)

**Comment by deweller** [comment]
I implemented this with a message like `MYTOKEN, FOOTOKEN and BARTOKEN are also accepted.`

![swapbot___adam_b__levine_s_ltbdisplay_swapbot](https://cloud.githubusercontent.com/assets/51414/8488337/a05b7eec-20d7-11e5-9d89-42e8531ac1c3.png)

**Comment by AdamBLevine** [comment]
Can you **Bold** alternative tokens selected to make them stand out more?
