### ISSUE TITLE
Simplified Swapbot Payment System

### ISSUE THREAD

**Issue by AdamBLevine** [tokenly/swapbot#108]
Please implement a flat-rate per-bot rental fee collection system that when paid runs 31 days for each time one of the monthly-payment amounts is paid.   Someone paying for a month gets 31 days, someone paying for 2 months gets 62 days.

The operator should be able to prepay whatever their desired amount.

When there are 3 days and 1 day remaining, an email should be sent to the operator prompting them to pay for another month.  If we can find a way to feel safe about sending the payment address via email, like using the same fee payment address per bot per operator so they can come to recognize the correct payment address, than I think that offers advantages over requiring them to log in to their account in order to top up for another month.

Tokens to accept:

$7 payable in BTC
60,000 LTBCOIN
1 TOKENLY

It would be great if it wasn't a code-level change to modify the amount of various tokens we accept, until we have non-BTC price feeds put in (and there aren't any good price feeds for LTBCOIN anyhow) I'll need to adjust rates manually periodically as the value of LTBCOIN appreciates because suddenly tokens have utility.

Fuel:
I propose we start paid accounts with enough tokenly-provided BTC fuel to power 10tx and just eat the cost to simplify things.  Users should be prompted via email to top-up the fuel when they have 3 and then 1 TX worth of fuel remaining.

**Comment by deweller** [comment]
I'm ok with just sending the address in the email.

Users can verify the address against previous sends in their wallet or click the link to their admin page and verify the address there.

It is possible that someone might spoof the email.  But the amount to gain from that is low ($7).


For funding the initial fuel, I will plan on taking the initial fuel out of the first month's (pre-paid) payment as it does now.

**Comment by deweller** [comment]
Moved the email notification about fuel to #114.

**Comment by AdamBLevine** [comment]
>"For funding the initial fuel, I will plan on taking the initial fuel out of the first month's (pre-paid) payment as it does now."

I don't think this will work given that we're accepting LTBCOIN and TOKENLY and probably XCP as well as BTC.  It'll work when people pay with BTC, but I was more concerned about keeping things simple for users who are redeeming a non-btc payment method

**Comment by AdamBLevine** [comment]
>In practice, fuel will rarely get used up now that OP_RETURN transactions are used.

So tx coming in and tx going out should be net-net?  In that case we'd just need a very small float on all swapbots.  Is that what you're thinking?

**Comment by deweller** [comment]
> I don't think this will work given that we're accepting LTBCOIN and TOKENLY and probably XCP as well as BTC.

Oh.  Right.  So I'll just set up a BTC fuel address that newly created swapbots can draw from for initial fuel.

> So tx coming in and tx going out should be net-net? In that case we'd just need a very small float on all swapbots. Is that what you're thinking?

Well, the dust should be net-net, but we do have to pay tx fees.  (I always forget about return fees.)  So, at the default of `0.0001 BTC` per tx fee, an initial fuel of 0.01 BTC ($2) should last about 100 swaps.

**Comment by deweller** [comment]
@AdamBLevine - Are you ok with this working on a monthly cycle rather than a strict 31 day cycle?  So if I pay on the 1st of the month, my next payment is due on the first of the next month even if it is March 1st?

**Comment by AdamBLevine** [comment]
Thats fine, I was thinking 31 days for simplicity but I see how it makes it more complicated.  I like your idea.
