### ISSUE TITLE
Group available swaps by token

### ISSUE THREAD

**Issue by cryptonaut420** [tokenly/swapbot#111]
When having a bot which sells multiple tokens, and accepting multiple types of tokens as well for each of those (for instance, selling SPONSOR and LTBDISPLAY tokens in the same bot, each accepting BTC, XCP and LTBCOIN as payment), the amount of "available swaps" that the interface shows adds up pretty quickly. It would be nicer if it grouped it into one entry for each token, and then able to expand it out to see what types of value tokens you can pay with.

**Comment by AdamBLevine** [comment]
Related to #105 and #104

**Comment by AdamBLevine** [comment]
@cryptonaut420 Have you tested multiple tokens being sold in the same bot?  We have been phrasing a Swapbot as a sells 1 Native token for many different tokens.

**Comment by cryptonaut420** [comment]
swapbot might not be suitable for vending multiple tokens in the same bot actually, difficult to determine what token an address is trying to buy. Will test this out. If not, we should have some sort of disclaimer or something or only allow one token to be vended out per bot (but able to accept multiple)

**Comment by AdamBLevine** [comment]
When setting up swaps we can just ask what Token the Swapbot will be selling, and then ask what Tokens they want to accept as a separate step.  My plan was to simply not allow people to set these up, BUT so long as there aren't any conflicts between prices it seems like this might actually work even with adjusting prices so long as ratios remain fixed.

**Comment by deweller** [comment]
If you create 2 swaps in the same bot and each accepts BTC, then it has no way of guessing the intent of the sender.

In this case, Swapbot will actually send BOTH tokens for the amount of BTC you sent.  This is usually not what you want.

We might want to warn against this functionality in the admin interface.

**Comment by cryptonaut420** [comment]
Is there any use case where someone would actually want to send more than one kind of token at the same time after receiving a single payment? seems like it will be less hassle and less confusion overall if people can only select one type of token to vend. But then again we also want to be able to have two way bots... e.g send in 0.01 BTC to get 1 EARLY token, or send in 1 EARLY token to get back 0.005 BTC or something like that.

**Comment by AdamBLevine** [comment]
There is no problem with that usecase @cryptonaut420 because there is only
one swap available when the bot dispensing EARLY recieves EARLY back.

So you can have

Many ->BUYFROMSWAPBOT-> NATIVE TOKEN
+
NATIVE TOKEN -> BUYFROMSWAPBOT -> Buyback Token @ Buyback Price

**Comment by cryptonaut420** [comment]
@AdamBLevine that is actually how I have it set up in the prototype, for that exact reason lol. There is a flag called "allow_two_way", which enables it to receive back the native vending token and send back something else. It can only send back one type of token though like you mention, so in the case of the prototype it just uses the first accepted token that you define.

For instance, you can see how I have BITCOINEX setup in the example gateways.php configuration file: https://github.com/tokenly/xcp-gateway/blob/master/conf/gateways.php

BITCOINEX = native token, and it accepts both BTC and XBTC, but it only buys back using BTC

**Comment by AdamBLevine** [comment]
We've determined that Swapbot as it is currently designed is not suitable for selling multiple tokens so we can close this issue.
