### ISSUE TITLE
Use Swapbot Heads as swapbot page favicon

### ISSUE THREAD

**Issue by AdamBLevine** [tokenly/swapbot#129]
![image](https://cloud.githubusercontent.com/assets/6858319/8336354/ae68b2dc-1a58-11e5-96d6-e9a578aebdd4.png)

Not sure how difficult this is so feel free to tell me i'm crazy, but I think the swapbot head that changes as the deal is modified would make a great favicon to help people tell apart different swapbots.

**Comment by AdamBLevine** [comment]
Looks good, can you please increase size by about 75%?  Compared to other icons or the SB admin circle the swapbot heads look quite small

**Comment by deweller** [comment]
See tokenly/php-robohash#1

**Comment by AdamBLevine** [comment]
noted, thanks
