### ISSUE TITLE
Need a public display of a swapbot

### ISSUE THREAD

**Issue by deweller** [tokenly/swapbot#13]
We have an admin panel.  But there needs to be a publicly viewable page as well.

This is where the details from #6 will be displayed.

**Comment by AdamBLevine** [comment]
Do we want to bring Marcin in at this point?

**Comment by deweller** [comment]
I'd like the 3 of us to talk through just a bit first.  

The first question is where will this live on the web?  On Let'sTalkBitcoin.com?  On swapbot.tokenly.co/public/early-bidirection-bot?

We have discussed a directory.  But the pieces are all starting to overlap and I want to get a clear picture so we can explain it to Marcin.

**Comment by AdamBLevine** [comment]
>The first question is where will this live on the web? On Let'sTalkBitcoin.com? On swapbot.tokenly.co/public/early-bidirection-bot?

The "Public Display" will be a dynamic page or content block generated for each swapbot and will contain a standard set of information about and regarding the swapbot it is focused on.

>We have discussed a directory. But the pieces are all starting to overlap and I want to get a clear picture so we can explain it to Marcin.

The directory is a way to, on a single webpage, find exactly the right swapbot for you to interact with based on your indicated desires.   It will pull the content block information from all the listed swapbots pages.

So the directory and the unique page share the same information but they are not the same thing.  We need a standard "this is what the front end of a single swapbot" looks like regardless of what page it is on.

**Comment by deweller** [comment]
We're thinking the public stats and information page for a bot will live on a URL like http://swapbot.co/public/early-bidirection-bot.

The long-term plan is to create an embeddable version of this for users to promote.

**Comment by AdamBLevine** [comment]
It might be good to naturally group bots by users, so  http://swapbot.co/public/dweller/early-bidirection-bot.

**Comment by deweller** [comment]
When presenting Marcin with the project, we should provide some sites that we like the design of so he can get a general idea of the look.

I gravitate toward simple, clean design.  
- I like github.com's design quite a bit.  They handle a lot of functionality and keep it pretty organized.
- I also like https://chain.so/BTC.  This site uses Bootstrap as a CSS template (so does my admin prototype).

**Comment by cryptonaut420** [comment]
I really like the idea of having the embeddable page, makes things really easy for people to just slap it on their websites or use it with the directory

**Comment by AdamBLevine** [comment]
What about something like Soundcloud?  https://soundcloud.com/mindtomatter/ltb-e184-epicenter-bitcoin-with-adam-b-levine

Allows for user customization (header image), Store Image (LTB Branding on the side), Critical Information about the machine and its current state superimposed over the header image, written description of mechanism and operator written flavor text below that.  

On the side we have the ability to let the operator link to redemption locations that the tokens being sold can be used (recommended) and then space for users to leave both operator (machine) reviews and token reviews

Operators with multiple machines could have their various properties displayed in this fashion, where all the information but the embeddable "core" that shares current bot state, inventory and prices would be listed as per https://soundcloud.com/mindtomatter while the rest of the page is branded to highlight the operator
