### ISSUE TITLE
Add basic Swapbot Operator Specific Branding

### ISSUE THREAD

**Issue by AdamBLevine** [tokenly/swapbot#135]
![image](https://cloud.githubusercontent.com/assets/6858319/8355450/3a7ff18a-1b04-11e5-99e1-8bd89ce03d8e.png)

Please add two fields to the Swapbot Admin interface

1. Upload and replace the background image (the boardwalk in all swapbots currently)
2. Change the color of the transparent color overlay (this would work either allowing any color or with a few primary presets that we know will look good)
3. Upload swapbot head size Logo (it should go in the highlighted area of the above image)

**Comment by deweller** [comment]
The overlay is implemented as a gradient.png file.  So that is the only option right now.  To add more gradients, we need images with different colors like this one:

http://swapbot.tokenly.com/images/background/gradient.png

I didn't make any of these.

**Comment by AdamBLevine** [comment]
So all that gradient image is is a few pixels tall, full width of a color?  Any particular opacity?  I'd love to get three or four more options.

**Comment by deweller** [comment]
Going to do a quick re-work of the gradient and implement it with CSS gradients instead.

**Comment by AdamBLevine** [comment]
thank  you :)

**Comment by deweller** [comment]
Will provide 3 pre-set options (and none?) for this pass.

**Comment by AdamBLevine** [comment]
Yes, Maybe Blue Green and Red or none?

**Comment by deweller** [comment]
Add the dimensions of images that should be uploaded.  it does not state them and they are non-intuitive.

For each of the colors, add light (30%), medium (60%), and heavy(90%) tint options.
