### ISSUE TITLE
Add basic Bulk Discount support

### ISSUE THREAD

**Issue by AdamBLevine** [tokenly/swapbot#139]
Now that we have users we're getting the natural requests for bulk discount programs and I think we should address them as soon as feasible with basic support.

I think the best way to accomplish this basic support is by using the concept of minimum order quantity (MOQ) thresholds and a % discount that would be taken into account by the calculator.

This would be done on a per-bot basis, the discount would be based on the number of tokens purchased in one transaction.

So if a token costs .01BTC, 10,000LTBc and 14 SWARM per token, which are all different prices, an operator would still only set the discount program once based on the size of the order

An operator could set a 10% discount at MOQ of 10, a 25% discount at MOQ 50, a 35% discount at MOQ 100.  That would mean that when someone spends more than 10 tokens worth at one time they would be asked to pay only 90% of the retail value in order to achieve the desired result.  Paying the normal rate will result in getting back more than you ordered which is not a bad outcome but is less desirable than communicating the savings.

When a user goes beyond a discount threshold, it replaces the one they had previously qualified for so the 10% discount does not exist for a user who qualifies for a 25% discount.  That 25% discount will apply to their whole order.

**Comment by AdamBLevine** [comment]
>So if a token costs .01BTC, 10,000LTBc and 14 SWARM per token, which are all different prices, an operator would still only set the discount program once based on the size of the order

Continuing this example, with the following discount arrangement

>MOQ  |  Discount
>1         |   0%
>10       | 10%
>50       | 25%
>100     | 35%

Would generate the following prices:

Order   | Discount | Total Price
7          | 0%          | 70,000LTBc, 0.07BTC or 98 SWARM
23        | 10%        | 207,000LTBc, 0.207BTC or 289.8 SWARM
51        | 25%        |382,500LTBc, 0.3825BTC or 535.5 SWARM

**Comment by AdamBLevine** [comment]
Devon, how ambitious is this project?  It would be really great to get this feature in, it would mean bots would become multi-purpose retail and wholesale as opposed to needing to pick one or maintain bots for both.

**Comment by AdamBLevine** [comment]
@deweller

**Comment by deweller** [comment]
Closed with 1a59d0962dc5c4491a03cfffaee85c3c82fc9120
