### ISSUE TITLE
Advanced Dynamic Pricing Options

### ISSUE THREAD

**Issue by cryptonaut420** [tokenly/swapbot#14]
We should implement some of the advanced pricing functionality that can be currently found in the Counterparty Gateway prototype script. You can see the code I made for these [here](https://github.com/tokenly/xcp-gateway/blob/master/lib/Gateway.php#L722) in the ```getLatestRate()``` function and example config for prototype [here](https://github.com/tokenly/xcp-gateway#installation)

Available price types:

**Fixed Rate / Fixed Amount**

Self explanatory, the most basic price type

**JSON API Feed**

User supplies 3 (required) things: 

* An endpoint (the URL)
* Data field, e.g which field in the response to grab the value from. If multiple levels deep, can string field name together such as "parent.child.child2.value"
* Request method, either GET or POST
* (optional) data.. basically just some JSON you can include with the request (e.g might need to include an API key or something). Should verify as valid JSON before accepting this
* (optional) modifier - a simple number thats multiplied by the request value. So for example you could say "I want my price to be 80% of whatever the value from this feed is"

**Counterparty Broadcast**

User supplies the source address of the broadcast as well as the "text" value. Swapbot then searches for the latest counterparty broadcast on the network that matches those values and uses that number for the price. Maybe an optional "modifier" that can be included as well. This would allow you to do things like control your swapbot prices directly from your counterwallet.

**Custom Function**

This one is more of a "only if you know how to program" one. With the prototype, I have a configuration file where you hardcode in the vending addresses and all their options, and can code in whatever custom functions etc.. useful for very advanced pricing. For instance I have one machine set up right now for one of my own tokens which looks at the last dividend paid out, and then runs a formula on that to determine a new price for the week. 

I'm thinking something kind of similar to [OpiDoki](https://www.youtube.com/watch?v=zlmk5tnoKBQ) for this. So basically you put in some javascript (probably limit the max length of it), and then it evaluates the result of that to determine the price. This is something that would be running frequently as a price checking mechanism and probably need to run server side. So I guess the main issue here is security concerns.. maybe have code running in a VM or something? not sure.. if nothing else, we could have this as something disabled for the public, but available to use on your own instance if you want. 

Another option that would be good to include for each vending machine is what to do if for some reason retrieving a dynamic price fails (e.g API server is down). Im thinking two choices; "use last price" where it just uses the last cached value, and "close machine", where the vending machine just becomes temporarily out of order until everything works again.

**Comment by AdamBLevine** [comment]
+1

**Comment by deweller** [comment]
going to split this into some different tasks.  See #25, #26 #15

**Comment by deweller** [comment]
And #27
