### ISSUE TITLE
Make an empty bot trigger the STOP warnings and apply a a warning to the ACTIVE state as well (active but empty)

### ISSUE THREAD

**Issue by AdamBLevine** [tokenly/swapbot#142]

**Comment by AdamBLevine** [comment]
In addition, where it currently says (blank) available it should instead say

**OUT OF STOCK** 

in red colored text

![image](https://cloud.githubusercontent.com/assets/6858319/8640529/c0032b92-28b0-11e5-8944-806594f2c0f8.png)

**Comment by deweller** [comment]
This is how the bot looks now for out of stock tokens:

![swapbot___btc_for_soup](https://cloud.githubusercontent.com/assets/51414/8689069/05c0b58c-2a69-11e5-8805-b908e73c503f.png)

I didn't do an overall "active but empty state" for the entire bot.  @AdamBLevine - Do you have a specific use case for that?  Or do you think the individual out of stock warnings will suffice.

**Comment by AdamBLevine** [comment]
ACK (I always wanted to say that, why do people say that on Github?)

As you surmised, this is sufficient and looks great.
