### ISSUE TITLE
Automated Income Forwarding

### ISSUE THREAD

**Issue by cryptonaut420** [tokenly/swapbot#16]
Users should be able to set up "income forwarding" rules for each machine. Put in your address, put in the token you want to be forwarded on, and then put in a quantity threshold. So for instance if you had a one way machine which sold SPONSOR for BTC, you could set it so everytime it reaches 1 BTC balance, it dumps that off to your cold storage wallet. Any transaction fees incurred etc. would be taken from your machines "BTC fuel"

**Comment by AdamBLevine** [comment]
Check out #9 for my thoughts on this one

**Comment by cryptonaut420** [comment]
Oh, yep good point, you have this covered already :p il close this one

**Comment by deweller** [comment]
I'm going to implement the income forwarding separately from the restocking functionality.  So this issue is open again to track that progress.
