### ISSUE TITLE
Trigger OUT OF STOCK notifications and warnings when inventory = zero

### ISSUE THREAD

**Issue by AdamBLevine** [tokenly/swapbot#161]
This swapbot was set up to sell one token at a time, currently our out of stock notifications do not activate until a swap that empties the bot has been completely completed even though the token is effectively unavailable to future buyers as soon as the order tx is detected on the blockchain, the wait is just confirming the payment is real before releasing the product to the buyer.

It would be better if the out of stock notifications became active as soon as the available quantity (inventory not allocated to in-progress swaps) reaches zero to avoid users trying to purchase what is not available and needing refunds that leave them unsatisfied.

![image](https://cloud.githubusercontent.com/assets/6858319/8750961/2c819ca2-2c5f-11e5-9c2c-952ed97b0f8a.png)

![image](https://cloud.githubusercontent.com/assets/6858319/8750980/4540cac4-2c5f-11e5-9964-b7070b0da57a.png)

**Comment by deweller** [comment]
Closed along with #169.  Will improved feedback with #174.
