### ISSUE TITLE
Stealing someone elses email notifcations

### ISSUE THREAD

**Issue by starsoccer** [tokenly/swapbot#163]
It seems it is possible to steal someone elses emails if when someone else purchase you also attempt to purchase using the same exact method that they did.

**Comment by AdamBLevine** [comment]
This isn't really a bug, more than one person can get email notifications on a tx - we don't really have a way of avoiding this outside of making people sign their transactions with a private key which is way intrusive.

Why do you think this is an issue given that everything is visible on the blockchain anyhow?

**Comment by deweller** [comment]
Interesting observation.

Swaps do allow for multiple people receiving emails about the same swap.  There is nothing in the email notifications that is not publicly available.

But this is good to keep in mind.

**Comment by starsoccer** [comment]
I didnt realize it was possible or intended. I assumed it as a bug because someone else receiving notifications for a transaction. I mean I guess in the end its not tho
