### ISSUE TITLE
SEO Friendly Bot Names

### ISSUE THREAD

**Issue by deweller** [tokenly/swapbot#164]
Allow users to create a url for their bot based on a wordpress-style slug.

This would let Swapbot urls to take the form of:

http://swapbot.tokenly.com/adam/adam-b-levines-ltbdisplay-swapbot

Should we enforce the username in the URL?  Or can even drop it down to:

http://swapbot.tokenly.com/adam-b-levines-ltbdisplay-swapbot

Each URL would need to be unique across all Swapbots.

**Comment by deweller** [comment]
I think we should keep the username but still require the url slug to be unique across all swapbots.

So there can't be a /adam/tokenly-for-btc-bot and a /devon/tokenly-for-btc-bot.  There will be only one or the other.

**Comment by AdamBLevine** [comment]
I think /user/bot naming convention makes sense
