### ISSUE TITLE
Add explainer text for Buffer funds

### ISSUE THREAD

**Issue by AdamBLevine** [tokenly/swapbot#167]
Regarding #56 

![image](https://cloud.githubusercontent.com/assets/6858319/8766614/a3da90d8-2df4-11e5-8b7a-b313e08f5a95.png)

The "why" is missing from this explanation, when a user mouses over the word "buffer" it should pop up this helper text

"Please deposit the additional buffer to avoid making the wrong payment since the price of bitcoin constantly moves and the tokens you are purchasing have a price set in dollars.    When you purchase from a swapbot your price is locked in the second the bot sees your transaction on the bitcoin network but during the few seconds between typing in the amount and sending , all excess is refunded and you may be refunded more than the buffer if the price of BTC goes up during that period"

I'll work on the copy more

Or something to that effect

**Comment by deweller** [comment]
I went with:

> The tokens you are purchasing have a price set in dollars. Since the price of bitcoin constantly changes, please deposit this additional buffer to make sure you send enough to complete your purchase.

> Your price is locked in the as soon as the bot sees your transaction on the bitcoin network. All excess is refunded and you may be refunded more than the buffer if the price of BTC goes up or less than the buffer if the BTC price goes down.
