### ISSUE TITLE
Configurable minimum purchase amounts

### ISSUE THREAD

**Issue by cryptonaut420** [tokenly/swapbot#18]
Ability to set optional minimum or maximum amounts of a token that can be purchased (or sold, should work both ways) within each swapbot. For example, setting it so you can only buy in a single purchase a minimum of 10,000 LTBCOIN and a maximum of 1,000,000. Amounts that go under just get refunded minus a tx fee, and for amounts that go over, sends the max amount and then the rest back as change. 

In the case of refunding/sending back change for non-BTC tokens, instead of subtracting from the total amount to cover the extra transaction, coin for transaction fees can be taken from the pool of "BTC Fuel" for that swapbot.

**Comment by deweller** [comment]
@cryptonaut420 - I see the need for a minimum.  But can you give me a use case for a maximum?

The refunding logic is somewhat complex. I am considering pushing the max to milestone v0.2 after we get some feedback.

**Comment by cryptonaut420** [comment]
maximum amount is definitely a very edge use case (nothing off the top of my head at the moment). I'd say push max back and stick with minimums for 0.1
