### ISSUE TITLE
Add payments calculator to admin backend

### ISSUE THREAD

**Issue by AdamBLevine** [tokenly/swapbot#182]
![image](https://cloud.githubusercontent.com/assets/6858319/9413138/f15c52ec-47e4-11e5-99f8-532556e8cf13.png)

I don't imagine having a full on event feed there but it would be nice if it could at least indicate when a payment has been detected without requiring a user to open the full feed.

**Comment by deweller** [comment]
See #114 - need to email admins when payment is due.
