### ISSUE TITLE
Add "Whitelist Only" Swap Mode

### ISSUE THREAD

**Issue by AdamBLevine** [tokenly/swapbot#196]
Not all bots are intended for public use, a bot should be able to be set to refund all incoming deposits that do not originate from a whitelisted address.  Bots should be able to be individually programmed with addresses or to look to a list hosted on a specific website in a compatible format.

**Comment by AdamBLevine** [comment]
Additional feature: Allow operator to set one or multiple "whitelist tokens" that convey whitelisted status to a purchasing address when it contains the token above operator defined amounts.

**Comment by deweller** [comment]
Implemented this as a simple configuration setting in the admin (very similar to blacklists).

I did not implement a URL to read a list from or a whitelist token in this implementation.  We can add those as separate issues as needed.

**Comment by deweller** [comment]
Need to extend the admin with a textarea to paste a bunch of addresses into for bulk uploads.  (No "file upload" but effectively the same thing, just copy and dump into the box.)

On output don't show all of the addresses if there are more than, say, 20.

**Comment by deweller** [comment]
Let's add the ability to manage large whitelists at the swapbot admin level, and then apply one at a time to different bots.

**Comment by deweller** [comment]
This is implemented at the admin level where CSV files are uploaded.  Individual Whitelist addresses can still be applied at the bot level.
