### ISSUE TITLE
Integrate Tawk.to live chat overlay into swapbot Admin and individual Bot pages

### ISSUE THREAD

**Issue by AdamBLevine** [tokenly/swapbot#203]
Here's the embed code.

<script type="text/javascript">
var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
(function(){
var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
s1.async=true;
s1.src='https://embed.tawk.to/561c5e42f207135a361e40d8/default';
s1.charset='UTF-8';
s1.setAttribute('crossorigin','*');
s0.parentNode.insertBefore(s1,s0);
})();
</script>

**Comment by cryptonaut420** [comment]
Actual embed code: http://pastebin.com/pg2nMrGB

@deweller this was actually super easy to add in, literally just copy pasting that code into your footer, took me like 30 seconds.
