### ISSUE TITLE
Add QR code

### ISSUE THREAD

**Issue by deweller** [tokenly/swapbot#211]
With the Indie Square wallet gaining popularity, it makes sense to show a QR code for SwapBot addresses.

Perhaps put it next to "To begin this swap, send 10 XCP to 1xxxxxxx".

I envision it as a small icon.  Clicking the icon will reveal a larger version that you can click out of to close.

**Comment by AdamBLevine** [comment]
Agreed on Rationale and Yep, sounds perfect to have an easy to expand icon.
