### ISSUE TITLE
Need to be able to end a swapbot

### ISSUE THREAD

**Issue by deweller** [tokenly/swapbot#22]
When a swapbot is done, the owner needs to be able to mark the bot as finished.

The bot should be marked as closed.

The owner should receive all funds and fuel left in the bot.

There should be a delay between when the bot is marked as closed and when it actually pays out.  So any transactions during the closing period can be refunded.

**Comment by cryptonaut420** [comment]
what about just a "deactivate" button which effectively closes it, and then once closed an additional option that allows you to claim all remaining funds? Some users might want to just temporarily disable the bot for whatever reason

**Comment by AdamBLevine** [comment]
Yep, I totally agree with that.  Again we're back to me wanting an auto-refund mode for the bot to go into because people just need the address and will often IMO not use the page.

**Comment by deweller** [comment]
+1

**Comment by AdamBLevine** [comment]
It would be interesting to incentivize people to not put their machine into unscheduled downtime by 

a. automating and standardizing the refund when machine down behavior
b. determine who pays the fee for the return transaction based on whether the downtime was scheduled.  If you do the "Scheduled Downtime Mode' approach where you set a time in advance to be advertised on the page at least 24hrs out and which will then update automatically with a "closed for business" sign than anyone sending to the machine still will pay the fee themselves while if you just go into immediate downtime mode than the store pays the fee for returns.

**Comment by deweller** [comment]
Copied from #52 

> Currently there is no way to shut down a Swapbot (unsuprisingly given we're quite early), there needs to be a button in the "edit" admin menu (considered sensitive with regards to #45)

> An admin wishing to shut down a swapbot should be able to pick a blacklisted or admin address on file from a drop-down menu (as a security measure) to dump all funds and tokens to.

**Comment by deweller** [comment]
I'm going to implement this as a permanent shutdown only.

If we want to add a temporary "Pause" button for swapbots, we can do that as a different function.

For shutdowns, I think the bot should go into refund-only mode for a certain timeframe (1 hour?) and then forward all tokens after that time to the owner.

Shutdowns are permanent and can't be canceled.
