### ISSUE TITLE
Token Registrar (remove XCP from registration process)

### ISSUE THREAD

**Issue by AdamBLevine** [tokenly/swapbot#23]
Regarding #10, we can add value by letting people register the asset they're going to sell in a new swapbot during the swapbot creation process.  Asset registration is a service any instance of swapbot can provide and in the case of someone creating an asset through us they would pay in bitcoin or ltbcoin or whatever in an amount worth say, 1 XCP or .75XCP where our cost will be .5XCP.

I realized this today when talking with a new podcaster who had lots of questions about setting up a SPONSOR style token but at the end told me he didnt know how or where to make a token, so I then had to point him to counterparty and actually gave him some XCP because its still hard to buy XCP with bitcoin unless you're on one of a few exchanges.   This would be a huge value add to let people register assets for Bitcoin.

**Comment by AdamBLevine** [comment]
I guess alternatively we can just provide good wallet software like LTB Companion that lets people easily create assets + provide swapbots that exchange BTC for XCP and the other way around.  Registering assets might be problematic from a legal perspective

**Comment by cryptonaut420** [comment]
I actually thought of something like this before, but as a separate, unrelated service. Basically like a domain registrar but registering asset names instead, and also a marketplace where people can buy and sell asset names which have already been registered

**Comment by AdamBLevine** [comment]
Right, that makes sense at some point but I think we can prototype the concept in swapbot since there will be of situations where people will need to create a bunch of tokens anyhow

**Comment by AdamBLevine** [comment]
Frankly this could be a core Tokenly service lol.

**Comment by AdamBLevine** [comment]
Coindaddy charges $5 payable + the USD cost of the token to register an asset on a users behalf payable in Bitcoin, Litecoin or dogecoin using Gocoin.com as their payment processor.

just a point of reference

**Comment by cryptonaut420** [comment]
this is going to be a separate thing from SwapBot, closing this
