### ISSUE TITLE
Configure Maximum Amounts

### ISSUE THREAD

**Issue by deweller** [tokenly/swapbot#24]
Split from #18 

> Ability to set optional maximum amounts of a token that can be purchased within each swapbot. For example, setting it so you can only buy a maximum of 1,000,000. For amounts amounts that go over, sends the max amount and then the rest back as change.

Is there a reason to configure a maximum?

**Comment by AdamBLevine** [comment]
I don't believe there is a reason to configure a maximum.  Even if a restock is required, the swapbots logic can just know it needs to complete the trade upon restock.
