### ISSUE TITLE
Email notifications of Swap Progress

### ISSUE THREAD

**Issue by AdamBLevine** [tokenly/swapbot#36]
During step 3 of the swapbot vending popup where you are "Waiting for Confirmations".

At this point the user has already selected their token, paid, and the system has recognized their transaction. All that is left to do is wait.

Since we don't need the user to do anything but wait, we should let them enter an email address (or username) and receive update notifications at three distinct stages.

1. Immediately upon listing the email to let the user know their request for updates went through properly, to tell them about the next two emails to expect and to give them an opportunity to cancel the remaining notifications in case someone signed up an email they did not own or other random nefarious or pranky things.

2. A second email would be sent when the transaction reaches the required number of confirmations to have the vending machine accept it and vend the purchased tokens back to the user.  

3. A third email would be send when the vending machine dispensing transaction has reached enough confirmations to ensure that when the user opens their wallet, it won't still be waiting for the tokens to show up.

**Comment by deweller** [comment]
For no. 3 above, I'm going to assume 1 confirmation is enough.  The time to reach consensus and for counterwallet to update the wallet balances is typically a matter of a few seconds.

The delay of receiving and reading the email and then going to check one's wallet will almost almost always going to be longer than the counterwallet delay.

**Comment by AdamBLevine** [comment]
Lets test it at 1, if I find myself beating the tokens to my wallet we'll move to two.  I think the ten minutes  extra before we tell them is much less annoying than ten more minutes of waiting after we've told them.
