### ISSUE TITLE
Add Blockchain.info link once user TX is identified or a vending tx occurs

### ISSUE THREAD

**Issue by AdamBLevine** [tokenly/swapbot#37]
When a user has paid in a swapbot purchase but is waiting for confirmations, there is no easy way to actually look at the transaction outside of the Swapbot experience.  At least in the beginning I think its important to have easy ways for people to vet that their transaction is behaving in a way they expect and we're not lying to them.

To that end, once the users TX has been identified we should provide an easy link that will pop up the blockchain.info transaction page or competing equivilent without closing the swapbot.  This could link either directly to the transactionid or simply to the originating address.

Similarly, once the swapbot has sent the dispensing TX, that should also be linked within the swapbot experience itself.

**Comment by deweller** [comment]
Marcin is designing a transaction details page.

This page will show the status of the swap while in process and be a permanent record of the swap when it is complete.

It will link to a blockchain explorer (counterpartychain.io?  blockchain.info?) with the bitcoin transaction IDs

**Comment by AdamBLevine** [comment]
does counterpartychain.io do bitcoin tx and counterparty assets?

Its very annoying that blockscan doesn't do bitcoin tx and requires me to use both blockchain and it to see the real contents of an address

if counterpartychain does both I say go with that

**Comment by deweller** [comment]
both just do counterparty transactions
