### ISSUE TITLE
"Return Transaction Fee" scale needs adjusting within Setup

### ISSUE THREAD

**Issue by AdamBLevine** [tokenly/swapbot#38]
When you are creating a new swapbot...

When you click the up or down arrows to modify the number, it moves it up or down by a full 1BTC which seems a bit much.  After clicking it once I actually forgot the original number and that was confusing too.

It would be good if tokenly could define lower and upper bounds for what an acceptable return transaction fee is, and it might range from .001 on the high end to .000001 for the low end.  Ideally clicking the up or down button would move the rate perhaps .00001 and you'd be able to enter a value without the buttons but it would be constrained by the upper and lower bounds as well.

**Comment by deweller** [comment]
I went with 0.00001 to a max of 0.001.  The step value has to be the same as the minimum (0.00001 in this case).

0.00001 is pretty low.  0.000001 is too low.  The transaction might not confirm for quite a while, especially if the UTXOs involved have been used recently.
