### ISSUE TITLE
When required confirms were complete, popup hung on step 3

### ISSUE THREAD

**Issue by AdamBLevine** [tokenly/swapbot#42]
The exact way this happened was I went through the process and while waiting for step 3 to confirm I clicked the wallet "next step" button, on which I then clicked another somewhat obvious button that I can't remember at the moment and it took me back to step 3 to wait but there was no longer a button that let me go to step four.

When the two confirmations were in, the popup correctly registered that 2/2 confirms were in but it did not move to another page and did not have an obvious path forward for how I should proceed.

On refreshing the page it took me to step 1 with no awareness of my previous transaction, although when I refreshed the main swapbot page it registered the swap as completed in Recent Swaps

**Comment by deweller** [comment]
I will address this as part of the new design pass implementation.
