### ISSUE TITLE
Swaps should not move to "Recent" until Vending TX has required # of confirms

### ISSUE THREAD

**Issue by AdamBLevine** [tokenly/swapbot#43]
Currently swaps are shifted from Active to Recent as soon as the payment to the vending machine is complete and/or the machine has made its vending transaction.

From the user perspective this is misleading because they might think the transaction is done so they can go to their wallet and find that the tokens are still not there because the network hasn't recieved them.

I propose keeping swaps in Active until a minimum of two confirmations of the vending transaction has been reached.  By that point the vast majority of wallets will have picked up and associated the tokens into the users actual control and so the experiance will be "The transcation finished and I had my tokens immediately" instead of " the transaction finished and I have to wait an indeterminate amount of time (because blocks are not consistent) before logging into my wallet to check.

**Comment by deweller** [comment]
Swaps now move into the recent list after 1 confirmation.  This is when swapbot considers a swap complete.
