### ISSUE TITLE
"Transaction Details" link at step 4 loops around to step 1

### ISSUE THREAD

**Issue by AdamBLevine** [tokenly/swapbot#44]
![image](https://cloud.githubusercontent.com/assets/6858319/7172258/5de7742e-e399-11e4-9b3e-de926085afe5.png)

**Comment by AdamBLevine** [comment]
When you click "transaction details" it loads this URL 

http://swapbot.dev01.tokenly.co/public/ltbstaff/64b21597-33a7-41a5-990f-3805feca314c/popup#

**Comment by deweller** [comment]
Acknowledged.  This will be fixed after we have a transaction details page to link to.  Needs #30.

**Comment by AdamBLevine** [comment]
Whoops, I thought that was going to Blockscan or similar.  Understood,
carry on!

**Comment by deweller** [comment]
This is fixed now.  This link goes to the transaction details page.
