### ISSUE TITLE
Refer to very small values of BTC as "Satoshis" rather than scientific notation

### ISSUE THREAD

**Issue by AdamBLevine** [tokenly/swapbot#46]
![image](https://cloud.githubusercontent.com/assets/6858319/7182882/f08a1696-e408-11e4-835e-b998a9defdbf.png)

Very few people understand what this means, we should use the friendlier "satoshis" terminology which refers to a unit of bitcoin denominated to .00000001

**Comment by deweller** [comment]
Should handle this along with #47.

**Comment by deweller** [comment]
Fixed as part of #106
