### ISSUE TITLE
Weird rounding in quantity calculation dealing with large decimals

### ISSUE THREAD

**Issue by AdamBLevine** [tokenly/swapbot#47]
![image](https://cloud.githubusercontent.com/assets/6858319/7182947/51e955a0-e409-11e4-80f7-0f497128d987.png)

Numbers like that show up for for lots of random values you might enter and not for others.  Given this is just an aproximation, we should simplify so it does not calculate beyond maybe 4 decimal places.

**Comment by deweller** [comment]
ahhh, floating point numbers...

**Comment by cryptonaut420** [comment]
+1 on this. should only show a max of 8 decimal places

e.g this is what im seeing "Waiting for 2 confirmations to send 0.004999999999992 BTC"

**Comment by deweller** [comment]
This was fixed while dealing with other related issues.
