### ISSUE TITLE
Make green wallet button a "Copy payment address to clipboard" button

### ISSUE THREAD

**Issue by AdamBLevine** [tokenly/swapbot#48]
![image](https://cloud.githubusercontent.com/assets/6858319/7183045/e9b9001a-e409-11e4-86d1-e76fc94c344d.png)

At some point in the future we might have hooks to load up a users wallet with the right token etc, but for now we are lacking a one-click copy-to-clipboard and the button would work well for it as currently placed.  Ideally a tool-tip would indicate it has been copied to your clipboard when you click it.

![image](https://cloud.githubusercontent.com/assets/6858319/7183058/fc321088-e409-11e4-8ab6-5ff6911bcd62.png)

**Comment by deweller** [comment]
This is a right arrow now.  The copy to clipboard functionality is covered in #58.
