### ISSUE TITLE
Need to add "Shut Down Swapbot" option

### ISSUE THREAD

**Issue by AdamBLevine** [tokenly/swapbot#52]
Currently there is no way to shut down a Swapbot (unsuprisingly given we're quite early), there needs to be a button in the "edit" admin menu (considered sensitive with regards to #45)

An admin wishing to shut down a swapbot should be able to pick a blacklisted or admin address on file from a drop-down menu (as a security measure) to dump all funds and tokens to.

**Comment by deweller** [comment]
Agreed.

Closing this in favor of #22.
