### ISSUE TITLE
Step 3s completion does not proceed to step 4

### ISSUE THREAD

**Issue by AdamBLevine** [tokenly/swapbot#55]
![image](https://cloud.githubusercontent.com/assets/6858319/7206683/9df0bd1e-e4e8-11e4-988d-e4cee48649c4.png)

It shows the details of the transaction but it does not proceed to the fourth and final step.  If the user does not need to proceed to the fourth step, it should at least stop saying Waiting for Confirmations

**Comment by deweller** [comment]
Ack.  Will fix as part #42.

**Comment by deweller** [comment]
Fixed with 7dd99926f06a50b7e4db3e9cb8829474e4234656.
