### ISSUE TITLE
Dealing with Fluctuating Exchange Rates - Overpay & Give Change or Tolerance

### ISSUE THREAD

**Issue by AdamBLevine** [tokenly/swapbot#56]
The only way for a customer to interact with a swapbot is to send tokens to its address.  This creates a problem when you have swapbot deals that are pegged to a specific dollar price.  What if the dollar:bitcoin price changes between the time a user decides to buy and gets their key out of cold storage to actually make the transaction.

Bitcoin routinely has 1% price variance hour-to-hour, a user sending the correct amount from their perspective might find they have underpaid and now either received most, but not all of a token that they will require all of to utilize.  On the other hand a user who pays as the rate moves in bitcoins favor might find that they have 103% of what is needed, meaning they have 3% that they don't need and that isn't very useful or valuable to them.  Not an ideal situation.

I see two possible paths forward

1. Simply expect that all vending transactions have at minimum two transfers, one that sends back the token being vended and the other sending back the change from the overpayment of bitcoin recieved.  If all user payments simply are asked to overpay by 2 or 3%, whether the price of bitcoin goes up by as much as 3% in the delay or down by any amount the second transaction refunds the difference between the actual price at the time of the vend and the overpayed amount.   This should work even when ordering multiple units of a given token.

2. Round up on purchases of 95% of a token, so the user is expected to pay 100% but they are vended a full token even if they only send 95%.  This would eliminate concerns about variance but make it possible to game the system and achieve a small discount.

This doesnt matter right now without prices pegged to dollars but we'll need it for easydomains

**Comment by AdamBLevine** [comment]
For 1 - We'd need to let users define what a "unit" of their token is, some tokens would have a trade denomination of 1, bitcoin might be .00001

**Comment by deweller** [comment]
Ideally the user would "lock" a price as part of the web-based checkout process.  You would get a quote that lasts for, say, 60 seconds.  As long as the bot sees an unconfirmed transaction within those 60 seconds then the quote is honored, even if the price changes by the time the input is confirmed.

We would then base our quote price on the averaged BTC price from the last, say, 10 minutes.  (I expect we can find a good formula for this).

This is more complicated, of course, but it might make for a good user experience.

**Comment by AdamBLevine** [comment]
@deweller But there is no connection between the front end and back end, isn't that an asset we should protect because it makes participation independent of the interface

**Comment by deweller** [comment]
I agree it should always be usable without the frontend.

We could make the connection just an illusion.  In reality there is no quote or lock on the price.  But when an unconfirmed transaction of BTC is received for a USD-based swap, then the swapbot looks at its recent history of BTC/USD conversion rate.  If the amount received matches anything that would have been valid in the last, say, 60 seconds - then the swapbot will treat this swap as if it had sent the exactly correct amount.

Think of this approach like No. 2 - but with a little added intelligence about recent BTC prices in order to prevent gaming of the system.

**Comment by AdamBLevine** [comment]
So the system gets updated pricing like every minute or two and basically it would use the last several buy-price-at-current-price as the possible accepted integers.

The only issue I see with this is that it doesn't help if someone pays a slightly wrong amount, where the "we always give change" no. 1 approach means that the exact amount of payment does not matter, you are expecting to overpay slightly and expecting to get back change.

**Comment by deweller** [comment]
Related to #25.

**Comment by AdamBLevine** [comment]
I see what you mean about the quote that refreshes every 60 seconds, this is in use at https://shapeshift.io with a constantly moving bar that fills up and refreshes the most current price.   

Honestly this is a harder problem for us than it is for shapeshift because since they deal with cryptocurrencies, those are generally investments and if you get .99 of a token it isn't a big deal because its basically the same value to you as 1.00 would be.  In our case with redeemable tokens, whole units matter a lot.  I can see an argument for not making some types of tokens divisible just to prevent "service dust" from accumulating in peoples wallets where you always find yourself with a few percentages of all the tokens you use that are left over.

I really like the "ask everybody to overpay 1 or 2 percent to handle all possible variance and refund them" method because it would avoid this problem entirely.

**Comment by deweller** [comment]
It occurs to me now that if users overpay a USD price using bitcoin, then we can refund them without even having to send a separate transaction.  We can include their refund in the BTC dust size along with the counterparty token.  So that makes the overpay solution great for BTC based payments.

I say we go forward with the overpay option.  But we only will accept USD-based pricing when people pay in bitcoin for now.

**Comment by AdamBLevine** [comment]
agreed, good insight on dust

**Comment by deweller** [comment]
Here is something I discovered while programming this.

The overpay approach works well for single expensive items.  For example, if I am purchasing a $100 chair token, then sending $102 worth of bitcoin and receiving change works great.

However, for purchasing many small tokens, an overpayment of 2% might get you more than you wished to purchase.  For example, say I am buying 100 candle tokens at $1 each.  If I send $102 worth of BTC, I will receive 102 CANDLETOKEN and no change.

My approach for now was to calculate a 2% market overpayment for expensive items.  For less expensive, indivisible tokens, the market overpayment is 40% of the cost of a single token (40 cents in the candle example).

Swapbot locks in the BTC price as soon as it sees the unconfirmed transaction.  So the time delay will be minimal in most cases.
