### ISSUE TITLE
Remove period and add "copy to clipboard" button to step 2

### ISSUE THREAD

**Issue by AdamBLevine** [tokenly/swapbot#58]
![image](https://cloud.githubusercontent.com/assets/6858319/7310842/f86c67a8-e9e7-11e4-90d5-5223f9513210.png)

**Comment by AdamBLevine** [comment]
Users will need to copy and paste the payment address, this issue deals with two current problems

1 - The period at the end of the address can and has been copied when the rest of the address is copied and that causes the transaction not to send because its an invalid address

2 - since every user needs to copy and paste the address we might as well save them the time and give them a copy-to-clipboard button to make it as simple as possible.

**Comment by deweller** [comment]
I created some instructional text and moved it above the waiting notification.  I added the copy to clipboard function there.

![swapbot](https://cloud.githubusercontent.com/assets/51414/7987349/93dbc3b6-0aa2-11e5-9cf8-c46d84ddcc45.png)
