### ISSUE TITLE
Show Bot Status, Activity and Logic to User on Bots Page

### ISSUE THREAD

**Issue by AdamBLevine** [tokenly/swapbot#6]
One of the least satisfying things about dealing with a token vending machine on the blockchain is the amount of uncertainty you face after you've made your irreversible send to the machine and before you know everything has gone well.

Even the simplest swapbot knows within seconds that the transaction seems to be fine and it knows to wait for a confirmation before sending its part of the swap.  We should communicate the following information(s) to users via each Swapbots user-facing page/interface

Further, we need to parse this information into human readable rather than straight transaction

So instead of

>Received 150000 LTBCOIN from 14dY2URUEteMkYieEyr4vNANusReqv7nrC with 3 confirmations. Sent 1.0005 EARLY to 14dY2URUEteMkYieEyr4vNANusReqv7nrC with transaction ID 30311a9fb5c948b3714898cce79df91a2bf8c7c177825a556434114b658d426a.

>Saw confirmed send of 1 EARLY to 14dY2URUEteMkYieEyr4vNANusReqv7nrC with transaction ID 30311a9fb5c948b3714898cce79df91a2bf8c7c177825a556434114b658d426a.

becomes 

"[Accepted 150,000LTBCOIN](http://blockscan.com/txInfo/11577278) at [Timestamp] and [Dispensed 1 EARLY](http://blockscan.com/txInfo/11577286)" at [timestamp]. 

* Details of all available swaps (what the machine swaps and all its rates and rules)
* Last 10 Swaps
* The Machines "State of Mind" i.e. "Idle" "Accepting" "Dispensing" "Reloading"
* The Order Que of the Machine, so when a transaction is seen its status is immediately displayed on the webpage for all users to see (without identity)

What other types of information do we want to share with users through this interface?

**Comment by deweller** [comment]
We'll show this on a public page. See #6
