### ISSUE TITLE
Add explainer text when prompting for email notifications

### ISSUE THREAD

**Issue by AdamBLevine** [tokenly/swapbot#60]
![image](https://cloud.githubusercontent.com/assets/6858319/7311645/e2af0720-e9f3-11e4-94d2-b420107b1441.png)

In bold it should say 
>"If this is your transaction, you're done!  Just leave your email and we'll let you know when your <type of token the user is going to recieve> have been delivered.

**Comment by AdamBLevine** [comment]
duplicated by #86

**Comment by deweller** [comment]
Closing this in favor of #86
