### ISSUE TITLE
Fuzzy transaction detection logic

### ISSUE THREAD

**Issue by AdamBLevine** [tokenly/swapbot#61]
Currently if a user indicates they'll be sending 20,000 LTBc but they only send 10,000LTBc the transaction is not detected and a user might just sit there unless they go back and change the amount to the amount they sent which would work fine.

It would be good to do a couple of things

1. Add some tolerence in general of perhaps 300% the specified amount to present as a possible candidate for their order
2. Let people click a button that says "I've paid" and that shows them all available transactions if theirs is not immediately obvious.
3. For now we can probably just show all users all transactions because volume is so low that users will likely not be using the swapbot at the same time unless we contrive a scenario.

**Comment by deweller** [comment]
I'd like to look for either an exact match or otherwise show all transactions.

My preference here is to do (2) which then does (3) when they click the I've paid link.

**Comment by deweller** [comment]
I did not add the tolerance.  I implemented (2) which does (3).
