### ISSUE TITLE
Add "change returned" to emails

### ISSUE THREAD

**Issue by AdamBLevine** [tokenly/swapbot#62]
>To recap your order, you sent <Swapbot name> <# of Tokens> <Type of tokens> and will be receiving [number of tokens] [Type of tokens> shortly.

Since we are adopting the overpay-and-give-change approach we should communicate about the change as well as the tokens

So new copy for the three emails should read

1
>To recap your order, you sent [Swapbot name] [# of Tokens] [Type of tokens] and will be receiving [number of tokens] [Type of tokens] along with [amount of change> bitcoin in change shortly.

2
>To recap your order, you sent [Swapbot name] [number of Tokens] [Type of tokens] and we’ve just sent you [number of tokens] [Type of tokens] along with [Amount of change] in bitcoin change.

3
>To recap your order, you sent [Swapbot name] [number of Tokens] [Type of tokens] and we've just delivered your [number of tokens] [Type of tokens] along with your [amount of change] in bitcoin change.

**Comment by deweller** [comment]
This will be applicable only when pricing in USD and users overpay bitcoin.

Related to #56 and #25.

**Comment by deweller** [comment]
I standardized this to `along with 0.01 BTC in change` in all 3 emails.

**Comment by AdamBLevine** [comment]
Is this merged with the staging server?  I'm not seeing it in the first email (still waiting on confs for the remaining)

![image](https://cloud.githubusercontent.com/assets/6858319/8111219/629e6f24-1015-11e5-9eb3-ce7c367dcd2b.png)

**Comment by deweller** [comment]
I left out the email sender process from my deploy script.  I fixed the script and deployed the email sender.

Any future emails should be the updated version going forward.

**Comment by AdamBLevine** [comment]
great, I have one more email (3rd) still waiting on a conf so i'll let you know
