### ISSUE TITLE
Swapbot sent its vending transaction 3 times

### ISSUE THREAD

**Issue by AdamBLevine** [tokenly/swapbot#64]
![image](https://cloud.githubusercontent.com/assets/6858319/7323881/be4ea840-ea66-11e4-8383-81d510edf2df.png)

**Comment by deweller** [comment]
Looks like this is a bug with xchain.   The XChain log reports: `Integrity constraint violation: 1062 Duplicate entry 'bf13c9941148313d33601dfad014f900863939140dfaea76172502d6b8e0c998'`

As such, xchain is sending the transaction, but reporting that is errored.

**Comment by deweller** [comment]
Here is what happened:

Counterpartyd was taking a long time to compose the send transaction.  In the mean time, XChain didn't hear back from swapbot in a reasonable amount of time, so it assumed swapbot didn't successfully receive the message that BTC had arrived.  So XChain sent another message to swapbot letting telling it that the BTC had arrived.  And swapbot processing another swap along with the first one.

I put some logic in place to handle this situation to never process the same XChain notification more than once.
