### ISSUE TITLE
Add ability to flip calculator perspective

### ISSUE THREAD

**Issue by AdamBLevine** [tokenly/swapbot#66]
![image](https://cloud.githubusercontent.com/assets/6858319/7327817/f9cdad08-ea84-11e4-83ec-443d29fa32b2.png)

There are two ways to look at any swap, either you're buying an amount of bitcoin with soup or you're selling an amount of soup for bitcoin.  If you think of it the first way than you know how much bitcoin you'll be getting you just don't know how much SOUP you need to send.  If you look at it the other way, you know how much SOUP you have to sell but don't know how much bitcoin it's going to be worth.

We should add the ability to flip between these perspectives.  Basically add two headings below the "Recieving Transactions" but above the progress dots that would be links or buttons controlling how it is displayed.  One would say "Sell SOUP for Bitcoin" the other says "Buy Bitcoin with Soup"  

Depending on which button is pressed the calculator would calculate accordingly.

**Comment by cryptonaut420** [comment]
I think this might be as simple as just separating the "accepted swaps" list on the admin interface into two sections: sell tokens and buy tokens. They would both be exactly the same, just there could be a "buy/sell" flag in the database that flips the wording and calculation on the front end.

**Comment by deweller** [comment]
Should we have the ability to both Sell and Buy tokens in the same bot?

![swapbot___satoshicard_bot](https://cloud.githubusercontent.com/assets/51414/8751335/e89dd8a8-2c71-11e5-9e56-4823e214f8e2.png)

Is this good or is that to much clutter on the front end interface?

**Comment by cryptonaut420** [comment]
@deweller yeah, thats what I am already doing with the SJCX and XCP bots (buying and selling). I dont think the clutter would be too bad especially now that the list of swaps is condensed. Make the "I want to buy" and "I want to sell" bigger and bolder to separate it better and it would be good IMO

**Comment by AdamBLevine** [comment]
Agreed - I want to buy / I want to sell distinctions in both the front end and admin interface seem like they would solve this problem with minimal issue

**Comment by AdamBLevine** [comment]
![image](https://cloud.githubusercontent.com/assets/6858319/9947820/123a19fe-5d52-11e5-9f94-cd6fc611213d.png)
I believe we've missed the mark on this one

Where it says "Tokens for Sale" it should say "Available Swaps" 

Where it says "Buy LTBCOIN" it should instead say "Sell TOKENLY for LTBCOIN" (multiple valid options do not exist when setting up a selling swap)

![image](https://cloud.githubusercontent.com/assets/6858319/9947866/9b703bea-5d52-11e5-9783-b209c02f8204.png)

The goal is to just let people type how much they want to sell and have it tell them how many of the other token they will receive.  Right now a user, if they want to sell 1.5 TOKENLY has to guess at how many LTBCOIN that is, type that amount in and then be told to pay the amount they want to pay.   This is backwards, here's how we can correct it.

Where it says "I would like to purchase _____ LTBCOIN" it should say
"I would like to sell ____ TOKENLY"

and the calculator will impact the TOKENLY variable against the fixed LTBCOIN rate rather than the LTBCOIN variable against the fixed TOKENLY rate

**Comment by deweller** [comment]
To change the second swap to selling TOKENLY instead of buying LTBCOIN, you can explicitly flip the perspective around in the admin interface.

@AdamBLevine - Can you take a look at how this works in the admin interface and see if that changes things?

**Comment by AdamBLevine** [comment]
My bad, I was looking at the wrong bot.

It looks good although I found an error

![image](https://cloud.githubusercontent.com/assets/6858319/9948361/29dfb186-5d57-11e5-8593-67897678acb6.png)

This is not useful information in this situation.

It would be best if it was the max # of TOKENLY that the bot is able to buy given the available inventory in the bot of the purchasing token.  It would also be good to have the rate (1 Tokenly = X LTBCOIN) available as well.

**Comment by deweller** [comment]
The bot calculated that 23.664906 is the maximum amount of TOKENLY it can buy based on the amount of BTC (0.23664906) in stock.

I'll make a separate issue to add the exchange rate on this screen.

**Comment by AdamBLevine** [comment]
you're way ahead of me :)
