### ISSUE TITLE
Soup transfer didn't register

### ISSUE THREAD

**Issue by AdamBLevine** [tokenly/swapbot#68]
http://blockscan.com/txInfo/11641894

**Comment by deweller** [comment]
Another process on the development server had a bug causing it to eat many server resources and caused xChain to get way behind.

I fixed the bug and xChain is catching up now.  It should be back to normal speed shortly.

**Comment by AdamBLevine** [comment]
Yup, caught up and everything sent properly except for some error html in the email which I referenced in #69
