### ISSUE TITLE
URL html in emails not resolving properly

### ISSUE THREAD

**Issue by AdamBLevine** [tokenly/swapbot#69]
![image](https://cloud.githubusercontent.com/assets/6858319/7330005/ef26deb2-ea9b-11e4-901e-64ebf5b47850.png)

**Comment by deweller** [comment]
Oops.  Forgot to unescape the HTML.

**Comment by AdamBLevine** [comment]
Not sure this is fixed?  Tested this after the most recent update pushed.

![image](https://cloud.githubusercontent.com/assets/6858319/7333841/97a1066c-eb32-11e4-9352-7da1d4643088.png)

**Comment by deweller** [comment]
I've run multiple email tests on my local system today and have not encountered this.  I'm pretty sure this is fixed on the live site now as well.
