### ISSUE TITLE
Always have "I Haven't Paid Yet" as an option that brings up bot payment information step 3

### ISSUE THREAD

**Issue by AdamBLevine** [tokenly/swapbot#71]
![image](https://cloud.githubusercontent.com/assets/6858319/7330106/8436bbde-ea9d-11e4-8870-ff5cac3aed1a.png)

Trying to buy 2 SOUP from the testbot I was not given any other option but to indicate that a transaction I'd made 7 hours prior was the one I wanted information on.  It was not.  I was trying to buy an additional two but this issue made that difficult (The bots payment address was shown but only in the receipt portion of the early transaction)

It would be good if two things happened

1 - If a transaction being detected has already completed, list it as "Completed Transactions - S" and list transactions that have less than 4 confirmations as "In Progress Transactions - Select yours to Continue"

2 - Always have a "I haven't paid yet" option along with the detected transactions so someone who hasn't paid can quickly get the info to do so.

**Comment by AdamBLevine** [comment]
Another example of the same problem

![image](https://cloud.githubusercontent.com/assets/6858319/7330198/c8d0e84a-ea9e-11e4-87a3-9993d9c741cf.png)

**Comment by deweller** [comment]
Completed swaps are automatically excluded from the list of swaps to choose from.  And the I haven't paid yet link will exclude any swap found that is currently in the list.
