### ISSUE TITLE
Two blocks hit very quickly and the green button from Step 3 to 4 didn't work

### ISSUE THREAD

**Issue by AdamBLevine** [tokenly/swapbot#73]
![image](https://cloud.githubusercontent.com/assets/6858319/7331397/5de9ab9c-eac2-11e4-8f24-6c38e84807ca.png)

**Comment by AdamBLevine** [comment]
![image](https://cloud.githubusercontent.com/assets/6858319/7331399/6fd49cae-eac2-11e4-870a-c4cf6a410a87.png)

**Comment by deweller** [comment]
This is an issue with not going on to the complete phase.  Will fix.

**Comment by deweller** [comment]
This was resolved along with #55.
