### ISSUE TITLE
Swapbot incoming transaction seems to wait for 100% confidence before asking a user if the transaction is theirs

### ISSUE THREAD

**Issue by AdamBLevine** [tokenly/swapbot#76]
in my opinion the swapbot should ask the user if the TX is theirs literally the second that it sees it on the network.  We know the transaction is not confirmed and could fail at that point so there is no sense waiting for it to be likely it will get confirmed as that makes the customer wait for between seconds and minutes unneccesarily.  

We just want to see that they have attempted to make the transaction, confirm to us that it is actually theirs and at that point our main goal becomes to collect their email address so we can update them as the process goes along.

Change requested: Make it absolutely as fast as possible for the web interface to go from detecting that a transaction is incoming to presenting it as an potential user payment for them to claim and follow.

**Comment by deweller** [comment]
XChain detects unconfirmed transactions and relays them as fast as possible to swapbot, which then pushes an update to the frontend.

You should not notice a delay of more than a second or two.  If there is a longer delay, then XChain or Swapbot is not working properly.
