### ISSUE TITLE
Swap Failed - Any more info?  It would be great to turn the error message into something that informs on next steps

### ISSUE THREAD

**Issue by AdamBLevine** [tokenly/swapbot#78]
![image](https://cloud.githubusercontent.com/assets/6858319/7335497/80701090-eb79-11e4-9b32-04eaddc2d6b3.png)

This is probably best in reference to #74

**Comment by AdamBLevine** [comment]
Yeah lets definitely rethink how failed swaps look and how long they stay on the list  
![image](https://cloud.githubusercontent.com/assets/6858319/7339524/92c3335a-ec26-11e4-9452-48ebcf6531c9.png)

**Comment by deweller** [comment]
There are now temporary errors and permanent errors.  Temproary errors will now have a message like "Continuing attempts to send 1,000 LTBCOIN".  

Permanent errors are unexpected errors and must be manually resolved by an admin.  They are considered complete and will move down to the recent swaps list.

**Comment by deweller** [comment]
Costomers are also emailed about a permanent error if they chose to enter their email address.
