### ISSUE TITLE
Add Email-on-Completion-or-Error option

### ISSUE THREAD

**Issue by AdamBLevine** [tokenly/swapbot#87]
Right now our email alert is very verbose, it sends three emails within about an hour updating a user as the transaction progresses.  Not all users care about anything outside of when they can use the tokens

In the highlighted area put "Only email me when my order has been delivered" with a checkbox where i've scribbled in red below the green button

![image](https://cloud.githubusercontent.com/assets/6858319/7529430/fe48cef4-f4ec-11e4-85b1-c30817162e3f.png)

This would cause the email being entered to only receive the third email, not either of the first two.  If the transaction error'd out for some reason, the user should be emailed.

**Comment by deweller** [comment]
I laid this out slightly differently.

![swapbot___btc_for_soup](https://cloud.githubusercontent.com/assets/51414/8792235/41f742ee-2f2a-11e5-85e6-411cee169b4e.png)
