### ISSUE TITLE
Make bots name and robohead a clickable link that takes you back to the bots front page. 

### ISSUE THREAD

**Issue by AdamBLevine** [tokenly/swapbot#88]
![image](https://cloud.githubusercontent.com/assets/6858319/7529502/bcf7bf58-f4ee-11e4-8bb2-71cdc99def9a.png)

**Comment by MorgUK** [comment]
And the logo please!

**Comment by AdamBLevine** [comment]
@MorgUK FYI the robohead is not the "logo", it's a security feature, for details see #77

**Comment by MorgUK** [comment]
@AdamBLevine OK, but as a web user I assume it's a logo and it's annoying that it's not clickable. In an ideal world everyone would read what the ChangeBot's speech bubble says, but many will just click the head assuming it's a logo to go back home. Is there going to be a separate logo/header before launch?

**Comment by AdamBLevine** [comment]
@MorgUK Good point, we can do both.

**Comment by cryptonaut420** [comment]
@devon this is pointing people to the wrong production domain.

For instance, if you go to a bot on http://swapbot.tokenly.com/

the head in the corner actually links to http://swapbot.web01.prod01.tokenly.co

**Comment by deweller** [comment]
I changed the domain in the configuration which resolved this.
