### ISSUE TITLE
Include swap receipt in email #3

### ISSUE THREAD

**Issue by AdamBLevine** [tokenly/swapbot#89]
They look great, we should send a copy to the user for their records
http://swapbot.dev01.tokenly.co/public/ltbstaff/swap/0a9e8c71-1e72-4d75-ad36-cc02427afee3

**Comment by deweller** [comment]
Are you thinking all of this information should be in the email?  Or can we just include a link to the receipt online?

**Comment by AdamBLevine** [comment]
It would be good to email it so we don't have to save and store every reciept ever generated forever
