### ISSUE TITLE
Automated Restocking and Overflow Addresses

### ISSUE THREAD

**Issue by AdamBLevine** [tokenly/swapbot#9]
We should allow users to set up staging addresses that users do not interact with but which contain restocking inventory.  The logic governing the address would watch the user-facing vending machine and whenever its balances dropped below a fixed minimum the restocking address tops off the vending machine.

Overflow addresses would simplify the process of keeping the correct amount of inventory on the vending machine rather than letting it accumulate earnings until fixed time periods.   A user could define the maximum amount of each token they are comfortable in keeping in the vending machine and in the restocking address, then provide the service with a bitcoin address under their control to receive any excess.

In a way, this can be thought of as the real profit - it is overflow beyond what is required to operate the system.

A swapbot would always first deal with the stocking of its restocking address, so backup inventory would stockpile there until the inventory is full of that token.  At the point that the inventory is full of that token, any more of that token would be swept (probably daily) into the overflow address.

**Comment by cryptonaut420** [comment]
I like this idea. Another thing we could do as an additional advanced option is just a simple web hook for when your vending machine runs out of tokens. So when it runs out, it makes a POST request to a specific URL you define, which could trigger some external logic to maybe refill the vending machine from elsewhere, do custom notifications or something

**Comment by AdamBLevine** [comment]
##+1 on the generic webhook improvement

**Comment by deweller** [comment]
This has been split into separate, smaller tasks.
