### ISSUE TITLE
Notify public users when the bot is inactive

### ISSUE THREAD

**Issue by deweller** [tokenly/swapbot#94]
When the bot becomes unpaid, we need to publish a warning of some kind of the public bot display page.

**Comment by deweller** [comment]
Oh - and make a note at the swap level as well.  Both before and after a swap is initiated.

**Comment by AdamBLevine** [comment]
Would it be crazy to give users the tools to restock a machine when they want what it contains and an operator hasn't gotten to it yet?

**Comment by deweller** [comment]
> Would it be crazy to give users the tools to restock a machine when they want what it contains and an operator hasn't gotten to it yet?

@AdamBLevine - I'm not following.  Could you elaborate?

**Comment by AdamBLevine** [comment]
@deweller the idea here was if a bot is inactive because it lacks BTC to pay for the vending tx, we could allow a user who really wants the token being sold to top up the fee address.

Honestly it's not a very good idea, please ignore it and lets move on :)

**Comment by AdamBLevine** [comment]
I think something like this on step 2 would be appropriate with a button that lets them send an email to the operator.

![image](https://cloud.githubusercontent.com/assets/6858319/8122019/e23f6b72-1068-11e5-88f0-c4909df89df7.png)

**Comment by deweller** [comment]
I did not implement the ability to email the operator.  We can push that to a later issue.
