### ISSUE TITLE
Integrate Multi-token URI scheme

### ISSUE THREAD

**Issue by AdamBLevine** [tokenly/swapbot#96]
To enhance ease-of-use with LTB Companion and Token Pockets wallet, please integrate the following scheme when displaying addresses so users may more easily send tokens to each other and avoid sending tokens to addresses that do not know how to see or deal with them.

The click-to-pay button would show up on step 2 of the Swapbot User Experiance, at this point the user has indicated the amount of tokens they are going to send and what specific type of token they will be sending. 

The click-to-pay button would filter the wallet for only that user-indicated single asset.

![image](https://cloud.githubusercontent.com/assets/6858319/7715711/269a3144-fe3f-11e4-94c5-738b18986149.png)

The click-to-pay button should be located centrally above the fully visible address as illustrated above.

**Implementation Examples**

Example that would accept BTC or any other single token only
`<span class="companion-tip-button" data-address="1Dhx3kGVkLaVFDYacZARheNzAWhYPTxHLq" data-label="bitcoin only" data-tokens="btc"></span>`

**Note: use all or no capitalization when describing date-tokens, LTBCOIN,FLDC,SJCX or ltbcoin,fldc,sjcx - mixed capitalization will not work.

**Comment by AdamBLevine** [comment]
Bump :)

**Comment by deweller** [comment]
The latest version of Tokenly Pockets (v0.1.4) uses a new syntax for payment buttons...  

`<span class="pockets-payment-button" data-address="19vsKtKFGXa1YBBGJzRTopf9onADrN77d5" data-label="Let's Talk Bitcoin! #227 Trezor and More!" data-tokens="btc,ltbcoin,tokenly"></span>`

Tokenly Pockets uses the `pockets-payment-button` class and LTB Companion uses `companion-tip-button` class,

**Comment by deweller** [comment]
Need a way to generate these via javascript.  See loon3/Tokenly-Pockets#4.

**Comment by deweller** [comment]
I added this on step 2, after the user has chosen the token to purchase and after they have chosen which token they wish to send.
